### ISSUE TITLE
Infinite loop when FREQ=MONTHLY when not provided with ByMonthDay or ByDay

### ISSUE THREAD

**Issue by julianooi** [graham/rrule#2]
Infinite loop when ByMonthDay and ByDay is not provided (even if StartDt is provided)

Tested with the following
"RRULE:FREQ=MONTHLY;INTERVAL=1"

Expected: error when parsing? or use StartDt's day as ByMonthDay

**Comment by bynov** [comment]
Hi, we have the same issue :(

**Comment by graham** [comment]
Merged (2 years late)
