### ISSUE TITLE
needs license

### ISSUE THREAD

**Issue by stevegt** [graham/rrule#5]
Hi @graham -- what license should we assume for this package?  [godoc](https://pkg.go.dev/github.com/graham/rrule) won't show the docs because there's no LICENSE file, and I'd also like to be able to make some contributions myself.

Would prefer MIT or GPL, but that's just my vote.

**Comment by graham** [comment]
Sorry for the delay, I've added the MIT license here: https://github.com/graham/rrule/blob/master/LICENSE

Thank you!

**Comment by graham** [comment]
Would love to have contributions to the library, feel free to send a PR and I'll do my best to merge it quickly!
